[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10.0

[font.bold]
style = "Bold"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
