#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM=xterm-256color

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ZSH Auto Suggestions
if [[ -s "${ZDOTDIR:-$HOME}/.zsh-autosuggestions/autosuggestions.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh-autosuggestions/autosuggestions.zsh"

  #  Enable autosuggestions automatically
  zle-line-init() {
    zle autosuggest-start
  }
  zle -N zle-line-init
fi
