#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM=xterm-256color

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Import local configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc_local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc_local"
fi

autoload -Uz zmv

alias vim='vim --servername vim'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
