#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM=xterm-256color
export EDITOR=vim
export VISUAL=vim
export GPG_TTY=$(tty)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Alias vim with servername if compiled with clientserver
[[ $(vim --clean --version --noplugin | grep -Eo "([-+])clientserver" | grep -Eo "[-+]") == "+" ]] &&\
  alias vim='vim --servername vim'

autoload -Uz zmv

# Import local configuration
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc_local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc_local"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
